version: '3'
services:
  postgres:
    image: 'postgres'
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    env_file: .env
    ports: 
      - '5400:5432'
  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwdpwd
    volumes:
      - ./pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
    logging:
      driver: none
  redis: 
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    ports:
      - '5001:5000'
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/node_modules
      - ./api:/app
    stdin_open: true
    tty: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGHOST=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  redis-server:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./redis
    volumes:
      - /app/node_modules
      - ./redis:/app
    stdin_open: true
    tty: true
    depends_on:
      - redis
