version: '3'
services:
  postgres:
    image: 'postgres'
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - '5400:5432'
  #stripe:
    #image: 'stripe/stripe-cli'
    #stdin_open: true
    #tty: true
  pgadmin:
    image: dpage/pgadmin4:4.22
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwdpwd
    volumes:
      - ./pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
    #command: 'echo "Set disable_coredump false" >> /etc/sudo.conf' 
    #sudo: setrlimit(RLIMIT_CORE): Operation not permitted (error fix)
    logging:
      driver: none
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - redis-server
      #- stripe
    volumes:
      - /app/node_modules
      - ./api:/app
    stdin_open: true
    tty: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGHOST=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  redis-server:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./redis-server
    volumes:
      - /app/node_modules
      - ./redis-server:/app
    stdin_open: true
    tty: true
