
FROM nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf

# add wget
#RUN apt-get update
#RUN apt-get install -y wget

# install certbot
#RUN wget https://dl.eff.org/certbot-auto
#RUN mv certbot-auto /usr/local/bin/certbot-auto
#RUN chown root /usr/local/bin/certbot-auto
#RUN chmod 0755 /usr/local/bin/certbot-auto

#configure ssl with nginx
#RUN /usr/local/bin/certbot-auto --nginx -y

# set up automatic renewal
#RUN echo "0 0,12 * * * root python -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/local/bin/certbot-auto renew -q" | sudo tee -a /etc/crontab > /dev/null

