module.exports = {
    REGISTER: 'REGISTER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    FETCH_USER_DATA: 'FETCH_USER_DATA',
    CLEAR_USER_DATA: 'CLEAR_USER_DATA',
    CHANGE_WEBSITE: 'CHANGE_WEBSITE'
}